name: Docker CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: |
          yourusername/flask-app:latest
          yourusername/flask-app:${{ github.sha }}
    
    - name: Deploy to server
      if: github.ref == 'refs/heads/main'
      run: |
        ssh ${{ secrets.SSH_HOST }} "
          docker pull yourusername/flask-app:latest &&
          docker-compose down &&
          docker-compose up -d
        "